# Generated by Django 3.1.6 on 2021-02-07 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='score',
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 11, 54, 45, 469705, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
