# Generated by Django 3.1.7 on 2021-02-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210222_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='covers'),
        ),
    ]
