# Generated by Django 3.1.6 on 2021-02-07 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210207_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 7, 12, 0, 38, 12556, tzinfo=utc), verbose_name='created at'),
            preserve_default=False,
        ),
    ]
