# Generated by Django 3.1.6 on 2021-02-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210218_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'ordering': ['id'], 'verbose_name_plural': 'Читатели'},
        ),
    ]
