# Generated by Django 3.1.7 on 2021-02-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210221_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankbooks',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='rankbooks',
            name='reader',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='RankBooks',
        ),
    ]
